from tkinter import *
root=Tk()
answer=StringVar()
disp=Entry(root,bg="blue",font=("bold",20),bd=20,textvariable= answer).grid(row=0,columnspan=4)
btn1=Button(root,text="1",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=1,column=0)
btn2=Button(root,text="2",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=1,column=1)
btn3=Button(root,text="3",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=1,column=2)
btn4=Button(root,text="4",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=2,column=0)
btn5=Button(root,text="5",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=2,column=1)
btn6=Button(root,text="6",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=2,column=2)
btn7=Button(root,text="7",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=3,column=0)
btn8=Button(root,text="8",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=3,column=1)
btn9=Button(root,text="9",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=3,column=2)
btn0=Button(root,text="0",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=4,column=2)
btn_add=Button(root,text="+",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=1,column=3)
btn_sub=Button(root,text="-",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=2,column=3)
btn_mul=Button(root,text="x",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=3,column=3)
btn_div=Button(root,text="%",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=4,column=0)
btn_equl=Button(root,text="=",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=4,column=1)
btn_clr=Button(root,text="CLR",padx=10,bg="white",fg="black",font=("bold",20)).grid(row=4,column=3)
root.mainloop()
